services:
  - type: web
    name: zero2prod
    runtime: docker
    plan: free
    healthCheckPath: /health_check
    envVars:
      - key: APP_ENVIRONMENT
        value: production
      - key: APP_APPLICATION_BASE_URL
        value: https://zero2prod-m5fi.onrender.com
      - key: APP_HMAC_SECRET
        generateValue: true
      - key: APP_REDIS_URI
        fromService:
          type: keyvalue
          name: zero2prod-redis
          property: connectionString
      - key: APP_EMAIL_CLIENT__SENDER_EMAIL
        sync: false
      - key: APP_EMAIL_CLIENT__AUTHORIZATION_TOKEN
        sync: false
      - key: APP_DATABASE__HOST
        fromDatabase:
          name: zero2prod-db
          property: host
      - key: APP_DATABASE__PORT
        fromDatabase:
          name: zero2prod-db
          property: port
      - key: APP_DATABASE__USERNAME
        fromDatabase:
          name: zero2prod-db
          property: user
      - key: APP_DATABASE__PASSWORD
        fromDatabase:
          name: zero2prod-db
          property: password
      - key: APP_DATABASE__DATABASE_NAME
        fromDatabase:
          name: zero2prod-db
          property: database

  - type: keyvalue
    name: zero2prod-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction

databases:
  - name: zero2prod-db
    databaseName: newsletter
    user: newsletter
    plan: free
