application_port: 8000
application_base_url: "http://127.0.0.1:8000"
hmac_secret: "0123456789012345678901234567890123456789012345678901234567890123"
redis_uri: "redis://127.0.0.1:6379"
database:
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "test@gmail.com"
  authorization_token: "POSTMARK_API_TEST"
